# docker-compose.yml
version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MYSQL_PASSWORD=rootpass
      - MYSQL_USERNAME=root
      - MYSQL_DB_NAME=volunteer_management
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - JWT_SECRET=secretofsecret
      - CORS_ORIGIN=http://localhost:3001
      - CLIENT_EMAIL_GOOGLE=nagarjun-mallesh-project@nagarjun-project.iam.gserviceaccount.com
      - PRIVATE_KEY_GOOGLE="-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCjmlUsIHnJF3qr\nWE8PxbwmMIdZcdv5pDPSJ+7lZHyDs9hzyzuwOZZA8Jh4IGbsse5bR3iXqNYXOwo1\nhB5P+GmygeE7Jk8HB36UNuaIB6RovWHGOckrh3unOn1wLaaXIMRwQGOEMJQ8IrjD\ncTvBCSsbzeoHGQzFuVBMKhwel/vWKTsuE12Su4p2SxSJJia67QIEWyzGoF8ovtz4\nBqV8IWdl+I4g1uZCPR8D7awZ2OB/9ckVy2Mwr1htNBivwW8ODJu7V+Ra8hPxihhA\ne63rRarO3+NEtScOOdRLKVNwKpdXSnklC+PW5sPdufnXnbxjJBspVxR494wAK/OX\nerf4mt4VAgMBAAECggEAAQ1djd6Zmer+PXrga0wMxTwbqr4aOZVORgQ+u5f1Ww19\nj2UXua7tIfbKLD+dGdmdHFYt1t/dnKGjE6wJW99PorfGIJDDAlsQe9iMjARskMXj\nCpjVi+OfrngoVV/dyewKh2RKn4+GbIqWoJ8qULgD4HZnEmudUuo5s3uz2ZiFpJ91\noRjIBsVyY4bwDANUMlaZKHpgORoHsE6qfl9f0xqmDK3gEO3pEEHt1VXO1f/6GAAX\nTYwbfuBv9RFWRV4OwyUjQkujx9j5AAAqzUM7lo53McvcWRkoENWcWnuGcq4c/Z0N\nYkE2YzV2JTvNAfrE1iDWznFM3qB/QoTQlg1cxZWy0wKBgQDUcj709LQVm6Pg/qDy\nEtV8uWPYHiOBPinqGNqB0Jn2ATeK3m+m/7yK0qHRGm8fnv2xDGOxvajKKGGUtz0U\n4nNm8tgCdSEQ+UJfm2KeWDHZTGSAmTO3eKqX9/gvkBPk7C+wHHWjbOovovFUamBd\nnYsKWKIh8SdoIPldL3DmJSyCmwKBgQDFJKcV/C9x1UrWpVHBw9ngWYWiHAj9Sz1O\njxTwqlSisaFIAld10det2DuoGLtiwKrGkTQKvXef4QmUPsVCqf0sn95HoyhCdGH1\nHow+xcJHyObMraDrL7hr8hbDLmZ12VA78Nd0sb8FYf2kpim+MGK/Qjekh5ceF6Li\naBHSdyGVDwKBgDB7Ufq8zUwRFLkH4trbiXTJKgvr9NZNxWry+Qqe/EOzy2UZlgla\nW0CjCOKbUbi5o9N/rFCno5le1cYGex4E/6kCymDlMgKZn5gJ8duI7PdWA6mFTNQV\n6Xh80lqoWqHndIqQNBhzho4QdVp6XDuA9HYL/BQa4I9W1xF4/h7HZPz5AoGBAIx7\nculSvMhkUqEkS19FXgPmJzj+u1UsAXLyuNxKtGb/J0u2B3b44rWKCfDeNuHHI6q+\nHBSvMQhoBzhxhoXbtoLPJUltNaotXwSaERxGNgyLWBRwgeQ2LDgX2iqZ7P97rRYZ\nqJ8KbnG6g1GJ6uMRfbyGxjnjOUeDVln6CQEuTWr3AoGAMh2V0ZTOQUunbMDKydmx\nbOqBcYCcIX8K70Piw+SogZNbFzEoKcKFsUfPOWEa/AUIdGyoktpKpR0UYthN7SC/\nN5CT3/JLZYShgsfQcz+L9Pda0kZ2Y7WW2FqTwiZaF0bUU46KTHpWny9AfsHxfp3k\nZ+cx9MN8wG26ww4vjylnRek=\n-----END PRIVATE KEY-----\n"
    networks:
      - internet-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql_test
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: volunteer_management
    volumes:
      - mysql_data:/var/lib/mysql
      - ./vp_db.sql:/docker-entrypoint-initdb.d/vp_db.sql
    networks:
      - internet-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local

networks:
  internet-network:
    driver: bridge