export const stateCities = {
    AL: ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa', 'Hoover', 'Auburn', 'Dothan', 'Decatur', 'Madison'],
    AK: ['Anchorage', 'Fairbanks', 'Juneau', 'Sitka', 'Ketchikan', 'Wasilla', 'Kenai', 'Kodiak'],
    AZ: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Glendale', 'Scottsdale', 'Gilbert', 'Tempe', 'Peoria'],
    AR: ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro', 'North Little Rock', 'Conway', 'Rogers'],
    CA: ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Long Beach', 'Oakland', 'Bakersfield', 'Anaheim'],
    CO: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood', 'Thornton', 'Arvada', 'Westminster'],
    CT: ['Bridgeport', 'New Haven', 'Hartford', 'Stamford', 'Waterbury', 'Norwalk', 'Danbury'],
    DE: ['Wilmington', 'Dover', 'Newark', 'Middletown'],
    FL: ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg', 'Hialeah', 'Tallahassee', 'Port St. Lucie'],
    GA: ['Atlanta', 'Augusta', 'Columbus', 'Macon', 'Savannah', 'Athens', 'Sandy Springs'],
    HI: ['Honolulu', 'Hilo', 'Kailua', 'Kaneohe', 'Pearl City'],
    ID: ['Boise', 'Nampa', 'Meridian', 'Idaho Falls', 'Pocatello', 'Caldwell'],
    IL: ['Chicago', 'Aurora', 'Naperville', 'Joliet', 'Rockford', 'Springfield', 'Peoria'],
    IN: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel', 'Bloomington', 'Fishers'],
    IA: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City', 'Ames'],
    KS: ['Wichita', 'Overland Park', 'Kansas City', 'Olathe', 'Topeka', 'Lawrence'],
    KY: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington'],
    LA: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles', 'Kenner'],
    ME: ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn'],
    MD: ['Baltimore', 'Columbia', 'Germantown', 'Silver Spring', 'Waldorf'],
    MA: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell', 'Brockton'],
    MI: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Lansing', 'Ann Arbor'],
    MN: ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington', 'Brooklyn Park'],
    MS: ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi'],
    MO: ['Kansas City', 'Saint Louis', 'Springfield', 'Columbia', 'Independence'],
    MT: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Butte'],
    NE: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney'],
    NV: ['Las Vegas', 'Reno', 'Henderson', 'Sparks', 'Carson City'],
    NH: ['Manchester', 'Nashua', 'Concord', 'Dover', 'Rochester'],
    NJ: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison'],
    NM: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell'],
    NY: ['New York', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse', 'Albany'],
    NC: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'],
    ND: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo'],
    OH: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton'],
    OK: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'],
    OR: ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro'],
    PA: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading', 'Scranton'],
    RI: ['Providence', 'Warwick', 'Cranston', 'Pawtucket'],
    SC: ['Columbia', 'Charleston', 'North Charleston', 'Mount Pleasant', 'Rock Hill'],
    SD: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings'],
    TN: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'],
    TX: ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi'],
    UT: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem'],
    VT: ['Burlington', 'South Burlington', 'Rutland', 'Barre'],
    VA: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Arlington', 'Newport News', 'Alexandria'],
    WA: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'],
    WV: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg'],
    WI: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'],
    WY: ['Cheyenne', 'Casper', 'Laramie', 'Gillette'],
    DC: ['Washington'],
    international: ['International']
};
